# Generated by Django 4.2.6 on 2023-10-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(3, 'admin'), (2, 'owner'), (1, 'broner')], default=1),
        ),
    ]
