# Generated by Django 4.2.6 on 2023-10-10 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stadiummodel',
            table='Stadium',
        ),
    ]
