# Generated by Django 4.2.6 on 2023-10-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0002_alter_stadiummodel_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadiummodel',
            name='stadium_bio_en',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='stadiummodel',
            name='stadium_bio_ru',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='stadiummodel',
            name='stadium_bio_uz',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='stadiummodel',
            name='stadium_name_en',
            field=models.CharField(default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='stadiummodel',
            name='stadium_name_ru',
            field=models.CharField(default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='stadiummodel',
            name='stadium_name_uz',
            field=models.CharField(default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='stadiummodel',
            name='stadium_rules_en',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='stadiummodel',
            name='stadium_rules_ru',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='stadiummodel',
            name='stadium_rules_uz',
            field=models.TextField(default='', null=True),
        ),
    ]
