# Generated by Django 4.2.6 on 2023-10-10 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BronModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bron_name', models.CharField(default='', max_length=120)),
                ('begin_time', models.DateTimeField(default=datetime.datetime.now)),
                ('end_time', models.DateTimeField(default=datetime.datetime.now)),
                ('free_time', models.DateTimeField(default=datetime.datetime.now)),
                ('broned', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Bron',
            },
        ),
    ]
